server:
  port: ${port:56010}


spring:
  application:
    name: serve-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
logging:
  level:
    root: info
    org.springframework: info